# A list of parameters to vary across each run
parameters:
  dataset_filename: [100marvelcharacters.csv]
  base_search_term: 
    - Marvel Comic Character
    - Character No Background
  search_style:
    - None
    - clipart
    - lineart
  search_domain: [None]
  optimizer:
    Adam:
      lr: [0.0001, 0.001, 0.01, 0.1]
    SGD:
      lr: [0.0001, 0.001, 0.01, 0.1]
      momentum: [0.9, 0.8, 0.7]
  test_size: [0.3]
  val_size: [0.1]
